### ISSUE TITLE
Traduzir README e CONTRIBUTING para inglês

### ISSUE THREAD

**Issue by lennontsky** [claramiranda/PrevisaoDoTempo#8]
Para que o projeto possa alcançar mais pessoas, é necessário que ele esteja disponível numa linguagem acessivel.

Precisamos que as orientações do README e do CONTRIBUTING sejam traduzidas e commitadas seguindo o padrão de nome abaixo

CONTRIBUTING-en.md
README-en.md

**Comment by cunhazera** [comment]
In progress

**Comment by lennontsky** [comment]
closed by #13 
@NelsonKommander
